baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "Kiera's Recipes"

[module]
[[module.imports]]
path = "github.com/tailwindlabs/tailwindcss"
[[module.mounts]]
source = "assets/css/main.css"
target = "assets/css/main.css"
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
